import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

const FoundersGrotesk = localFont({
  src: "../../public/fonts/FoundersGrotesk-Regular.otf",
  variable: "--font-founders-grotesk",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Analytics />
      <html lang="en" className={`${FoundersGrotesk.variable}`}>
        <body className={FoundersGrotesk.className}>{children}</body>
      </html>
    </>
  );
}
